In [2]:
import pandas as pd
import numpy as np
from pandas import DataFrame, Series
import re

In [24]:
df = pd.DataFrame(columns=['idx', 'date'])
report = pd.read_csv("../final_data/bond_pre.csv")

for i in range(report.shape[0]):
    report_date = report["date"][i]
    report_date = report_date[0:7]
    df = df.append(pd.DataFrame([[i, report_date]], columns=['idx', 'date']), ignore_index=True)
    df = df.sort_values(["date"], ascending=True )
    
df.set_index('idx', inplace=True)
df = df.groupby("date").size()
print(df)
    
#     report_date = report_date.sort_values(["date"], ascending=[False])

date
2008.04     6
2008.05    13
2008.06    21
2008.07    29
2008.08    28
2008.09    28
2008.10    29
2008.11    26
2008.12    27
2009.01    25
2009.02    26
2009.03    29
2009.04    28
2009.05    24
2009.06    29
2009.07    29
2009.08    26
2009.09    34
2009.10    49
2009.11    50
2009.12    48
2010.01    39
2010.02    10
2010.03     8
2010.04     7
2010.05     6
2010.06     6
2010.07     8
2010.08    15
2010.09    34
           ..
2015.07    41
2015.08    42
2015.09    47
2015.10    59
2015.11    58
2015.12    57
2016.01    63
2016.02    55
2016.03    60
2016.04    42
2016.05    41
2016.06    38
2016.07    28
2016.08    41
2016.09    32
2016.10    31
2016.11    23
2016.12    24
2017.01    30
2017.02    29
2017.03    19
2017.04    36
2017.05    33
2017.06    36
2017.07    44
2017.08    31
2017.09    34
2017.10    33
2017.11    49
2017.12    19
Length: 117, dtype: int64

In [25]:
df.to_csv("../final_data/bond_count_month.csv")
print(df)

date
2008.04     6
2008.05    13
2008.06    21
2008.07    29
2008.08    28
2008.09    28
2008.10    29
2008.11    26
2008.12    27
2009.01    25
2009.02    26
2009.03    29
2009.04    28
2009.05    24
2009.06    29
2009.07    29
2009.08    26
2009.09    34
2009.10    49
2009.11    50
2009.12    48
2010.01    39
2010.02    10
2010.03     8
2010.04     7
2010.05     6
2010.06     6
2010.07     8
2010.08    15
2010.09    34
           ..
2015.07    41
2015.08    42
2015.09    47
2015.10    59
2015.11    58
2015.12    57
2016.01    63
2016.02    55
2016.03    60
2016.04    42
2016.05    41
2016.06    38
2016.07    28
2016.08    41
2016.09    32
2016.10    31
2016.11    23
2016.12    24
2017.01    30
2017.02    29
2017.03    19
2017.04    36
2017.05    33
2017.06    36
2017.07    44
2017.08    31
2017.09    34
2017.10    33
2017.11    49
2017.12    19
Length: 117, dtype: int64